// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import HeaderSlice from './HeaderSlice';
import HeroSlice from './HeroSlice';
import Image from './Image';
import ImageGroup from './ImageGroup';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	HeaderSlice,
	HeroSlice,
	Image,
	ImageGroup,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	header_slice: HeaderSlice,
	hero_slice: HeroSlice,
	image: Image,
	image_group: ImageGroup,
	quote: Quote,
	text: Text,
};
